version: '3'

services:
  db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: hero_development
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    ports:
      - '5306:3306'
  nuxt:
    build: ./nuxt
    container_name: 'hero_nuxt'
    command: yarn dev
    volumes:
      - ./nuxt:/usr/my_projects
      - ./nuxt/node_modules:/usr/my_projects/node_modules
    ports:
      - '5600:3000'
  laravel:
    image: palladion/pl-laravel
    command: php artisan serve --host 0.0.0.0 --port=3000
    ports:
      - 4000:3000
    volumes:
      - ./laravel:/usr/my_projects
